<a href="https://colab.research.google.com/github/swathi-ganesula/Machine-Learning/blob/main/LOOCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.model_selection import LeaveOneOut,LeavePOut

In [ ]:
loocv=LeaveOneOut()

In [ ]:
loocv

LeaveOneOut()

In [ ]:
num=np.arange(10,20)

In [ ]:
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
res=loocv.split(num)

In [ ]:
res

<generator object BaseCrossValidator.split at 0x7ea51e3daa40>

In [ ]:
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
var=list(res)

In [ ]:
var

[(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0])),
 (array([0, 2, 3, 4, 5, 6, 7, 8, 9]), array([1])),
 (array([0, 1, 3, 4, 5, 6, 7, 8, 9]), array([2])),
 (array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([3])),
 (array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4])),
 (array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([5])),
 (array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([6])),
 (array([0, 1, 2, 3, 4, 5, 6, 8, 9]), array([7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 9]), array([8])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([9]))]

In [ ]:
list(res)

[]

In [ ]:
var

[(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0])),
 (array([0, 2, 3, 4, 5, 6, 7, 8, 9]), array([1])),
 (array([0, 1, 3, 4, 5, 6, 7, 8, 9]), array([2])),
 (array([0, 1, 2, 4, 5, 6, 7, 8, 9]), array([3])),
 (array([0, 1, 2, 3, 5, 6, 7, 8, 9]), array([4])),
 (array([0, 1, 2, 3, 4, 6, 7, 8, 9]), array([5])),
 (array([0, 1, 2, 3, 4, 5, 7, 8, 9]), array([6])),
 (array([0, 1, 2, 3, 4, 5, 6, 8, 9]), array([7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 9]), array([8])),
 (array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([9]))]

In [ ]:
for i in res:
  print(i)

In [ ]:
a=100
print(a)

100


In [ ]:
b="zebra"
print(id(b))

139247509875200


LEAVE P OUT

In [ ]:
from sklearn.model_selection import LeavePOut

In [ ]:
lpocv=LeavePOut(p=2)

In [ ]:
lpocv

LeavePOut(p=2)

In [ ]:
num


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
res1=lpocv.split(num)

In [ ]:
res1

<generator object BaseCrossValidator.split at 0x7ea51566ad40>

In [ ]:
for i in res1:
  print(i)

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1]))
(array([1, 3, 4, 5, 6, 7, 8, 9]), array([0, 2]))
(array([1, 2, 4, 5, 6, 7, 8, 9]), array([0, 3]))
(array([1, 2, 3, 5, 6, 7, 8, 9]), array([0, 4]))
(array([1, 2, 3, 4, 6, 7, 8, 9]), array([0, 5]))
(array([1, 2, 3, 4, 5, 7, 8, 9]), array([0, 6]))
(array([1, 2, 3, 4, 5, 6, 8, 9]), array([0, 7]))
(array([1, 2, 3, 4, 5, 6, 7, 9]), array([0, 8]))
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([0, 9]))
(array([0, 3, 4, 5, 6, 7, 8, 9]), array([1, 2]))
(array([0, 2, 4, 5, 6, 7, 8, 9]), array([1, 3]))
(array([0, 2, 3, 5, 6, 7, 8, 9]), array([1, 4]))
(array([0, 2, 3, 4, 6, 7, 8, 9]), array([1, 5]))
(array([0, 2, 3, 4, 5, 7, 8, 9]), array([1, 6]))
(array([0, 2, 3, 4, 5, 6, 8, 9]), array([1, 7]))
(array([0, 2, 3, 4, 5, 6, 7, 9]), array([1, 8]))
(array([0, 2, 3, 4, 5, 6, 7, 8]), array([1, 9]))
(array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3]))
(array([0, 1, 3, 5, 6, 7, 8, 9]), array([2, 4]))
(array([0, 1, 3, 4, 6, 7, 8, 9]), array([2, 5]))
(array([0, 1, 3, 4, 

In [ ]:
lpocv2=LeavePOut(p=5)

In [ ]:
lpocv2

LeavePOut(p=5)

In [ ]:
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
res3=lpocv2.split(num)

In [ ]:
res3

<generator object BaseCrossValidator.split at 0x7ea51566af40>

In [ ]:
result=list(res3)

In [ ]:
result

[(array([5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4])),
 (array([4, 6, 7, 8, 9]), array([0, 1, 2, 3, 5])),
 (array([4, 5, 7, 8, 9]), array([0, 1, 2, 3, 6])),
 (array([4, 5, 6, 8, 9]), array([0, 1, 2, 3, 7])),
 (array([4, 5, 6, 7, 9]), array([0, 1, 2, 3, 8])),
 (array([4, 5, 6, 7, 8]), array([0, 1, 2, 3, 9])),
 (array([3, 6, 7, 8, 9]), array([0, 1, 2, 4, 5])),
 (array([3, 5, 7, 8, 9]), array([0, 1, 2, 4, 6])),
 (array([3, 5, 6, 8, 9]), array([0, 1, 2, 4, 7])),
 (array([3, 5, 6, 7, 9]), array([0, 1, 2, 4, 8])),
 (array([3, 5, 6, 7, 8]), array([0, 1, 2, 4, 9])),
 (array([3, 4, 7, 8, 9]), array([0, 1, 2, 5, 6])),
 (array([3, 4, 6, 8, 9]), array([0, 1, 2, 5, 7])),
 (array([3, 4, 6, 7, 9]), array([0, 1, 2, 5, 8])),
 (array([3, 4, 6, 7, 8]), array([0, 1, 2, 5, 9])),
 (array([3, 4, 5, 8, 9]), array([0, 1, 2, 6, 7])),
 (array([3, 4, 5, 7, 9]), array([0, 1, 2, 6, 8])),
 (array([3, 4, 5, 7, 8]), array([0, 1, 2, 6, 9])),
 (array([3, 4, 5, 6, 9]), array([0, 1, 2, 7, 8])),
 (array([3, 4, 5, 6, 8]), array

In [ ]:
result

[(array([5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4])),
 (array([4, 6, 7, 8, 9]), array([0, 1, 2, 3, 5])),
 (array([4, 5, 7, 8, 9]), array([0, 1, 2, 3, 6])),
 (array([4, 5, 6, 8, 9]), array([0, 1, 2, 3, 7])),
 (array([4, 5, 6, 7, 9]), array([0, 1, 2, 3, 8])),
 (array([4, 5, 6, 7, 8]), array([0, 1, 2, 3, 9])),
 (array([3, 6, 7, 8, 9]), array([0, 1, 2, 4, 5])),
 (array([3, 5, 7, 8, 9]), array([0, 1, 2, 4, 6])),
 (array([3, 5, 6, 8, 9]), array([0, 1, 2, 4, 7])),
 (array([3, 5, 6, 7, 9]), array([0, 1, 2, 4, 8])),
 (array([3, 5, 6, 7, 8]), array([0, 1, 2, 4, 9])),
 (array([3, 4, 7, 8, 9]), array([0, 1, 2, 5, 6])),
 (array([3, 4, 6, 8, 9]), array([0, 1, 2, 5, 7])),
 (array([3, 4, 6, 7, 9]), array([0, 1, 2, 5, 8])),
 (array([3, 4, 6, 7, 8]), array([0, 1, 2, 5, 9])),
 (array([3, 4, 5, 8, 9]), array([0, 1, 2, 6, 7])),
 (array([3, 4, 5, 7, 9]), array([0, 1, 2, 6, 8])),
 (array([3, 4, 5, 7, 8]), array([0, 1, 2, 6, 9])),
 (array([3, 4, 5, 6, 9]), array([0, 1, 2, 7, 8])),
 (array([3, 4, 5, 6, 8]), array

In [ ]:
len(result)

252